In [1]:
#Import required libraries
import numpy as np
import pandas as pd
import pandas as pd
from math import pow, sqrt
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
from fuzzywuzzy import process
import warnings
warnings.filterwarnings('ignore')

d:\softwares\python3\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [2]:
#Read data to pandas dataframe
ratings = pd.read_csv('dataset.csv') 

In [3]:
#print dataframe
ratings

user_id sex  age     occupation  \
0          173   M   56          other   
1          607   F   49     healthcare   
2          600   M   34     programmer   
3          104   M   27        student   
4          486   M   39       educator   
5          372   F   25        student   
6           94   M   26        student   
7          188   M   42        student   
8          297   F   29       educator   
9          329   M   48       educator   
10         498   M   26         writer   
11         588   F   18        student   
12         527   M   33      librarian   
13         110   M   19        student   
14         251   M   28         doctor   
15         522   M   36       engineer   
16         373   F   24          other   
17          85   M   51       educator   
18          49   F   23        student   
19         693   F   43     healthcare   
20          86   M   26  administrator   
21         448   M   23  entertainment   
22         919   M   25          other   
23         474   M   51      executive   
24         294   M   34     technician   
25         381   M   33         artist   
26         154   M   25        student   
27         533   M   43      librarian   
28         389   F   44         writer   
29         896   M   28         writer   
...        ...  ..  ...            ...   
79970      143   M   42     technician   
79971      173   M   56          other   
79972      276   M   21        student   
79973      447   M   30  administrator   
79974      268   M   24       engineer   
79975      367   M   17        student   
79976      641   M   24        student   
79977      303   M   19        student   
79978      271   M   51       engineer   
79979      766   M   42          other   
79980      535   F   45       educator   
79981       13   M   47       educator   
79982      387   M   33  entertainment   
79983      368   M   18        student   
79984      868   M   21     programmer   
79985        7   M   57  administrator   
79986      268   M   24       engineer   
79987      135   M   23        student   
79988      463   F   48     healthcare   
79989      363   M   20        student   
79990      247   M   28       engineer   
79991      873   F   48  administrator   
79992      447   M   30  administrator   
79993      870   M   22        student   
79994      757   M   26        student   
79995      683   M   42      librarian   
79996      191   M   33  administrator   
79997      625   M   27     programmer   
79998      128   F   24      marketing   
79999      847   M   29        student   

                                             movie title  movie_id  rating  \
0                                           Evita (1996)       289       4   
1                         Raiders of the Lost Ark (1981)       174       3   
2                            Natural Born Killers (1994)        53       4   
3                             Beverly Hills Ninja (1997)       456       3   
4                                Frighteners, The (1996)       123       3   
5                                          Scream (1996)       288       5   
6                                      Casablanca (1942)       483       5   
7                                           Speed (1994)       568       4   
8                                           Alien (1979)       183       4   
9                             Singin' in the Rain (1952)       705       3   
10                                    Taxi Driver (1976)        23       4   
11                                     Pocahontas (1995)       542       3   
12                      In the Name of the Father (1993)       317       4   
13                                    Bushwhacked (1995)      1246       2   
14                            Grosse Pointe Blank (1997)       248       4   
15                             North by Northwest (1959)       480       5   
16                                    Under Siege (1992)       233       3  

In [4]:
#Rearranging dataframe
moviemat = ratings.pivot_table(index='user_id',columns='movie_id',values='rating').fillna(0)
moviemat.head()

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
1          5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2          4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
5          4.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   

movie_id  1669  1670  1671  1672  1674  1677  1678  1680  1681  1682  
user_id                                                               
1          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 1649 columns]

In [5]:
#converting dataset to CSR matrix
mat = csr_matrix(moviemat.values)

In [6]:
#Using KNN algorithm with cosine similarity
model_knn=NearestNeighbors(metric="cosine",algorithm="brute")
model_knn.fit(mat)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [7]:
#Testing model for index 0
query_index=0

recommended=[] 
distance,indice=model_knn.kneighbors(moviemat.iloc[query_index,:].values.reshape(1,-1),n_neighbors=6)
print("Distance:",distance," Indice :",indice)
 
print(distance.flatten())
print(len(distance.flatten()))
 
for i in range(0,len(distance.flatten())):
    if i==0:
        print("Recommendation for {0}:\n".format(moviemat.iloc[query_index,:]))
    else:
        print("{0}: {1}, with calculated distance = {2}:".format(i,moviemat.index[indice.flatten()[i]],distance.flatten()[i]))
        recommended.append(moviemat.index[indice.flatten()[i]])


    print(recommended)

Distance: [[1.55431223e-15 4.94422473e-01 5.12465121e-01 5.25721913e-01
  5.27326314e-01 5.44148221e-01]]  Indice : [[  0 434 267 915 428 456]]
[1.55431223e-15 4.94422473e-01 5.12465121e-01 5.25721913e-01
 5.27326314e-01 5.44148221e-01]
6
Recommendation for movie_id
1       5.0
2       3.0
3       4.0
4       3.0
5       3.0
6       5.0
7       4.0
8       1.0
9       5.0
10      3.0
11      2.0
12      5.0
13      5.0
14      0.0
15      5.0
16      0.0
17      3.0
18      4.0
19      5.0
20      4.0
21      1.0
22      4.0
23      4.0
24      3.0
25      4.0
26      3.0
27      0.0
28      0.0
29      1.0
30      3.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
N

In [8]:
#Writing recommendations to file
myfile = open('recommended.txt', 'w')

for userid in range(0,943):
    myfile.write("\n") 
    query_index=userid
    myfile.write(str(query_index+1))
    recommended=[] 
    distance,indice=model_knn.kneighbors(moviemat.iloc[query_index,:].values.reshape(1,-1),n_neighbors=6)
    print("Distance :",distance," Indice :",indice)

    print(distance.flatten())
    print(len(distance.flatten()))

    for i in range(0,len(distance.flatten())):
        if i==0:
            print("Recommendation for {0}:\n".format(moviemat.iloc[query_index,:]))
        else:
            print("{0}: {1}, with distance of {2}:".format(i,moviemat.index[indice.flatten()[i]],distance.flatten()[i]))
            recommended.append(moviemat.index[indice.flatten()[i]])
    print(recommended)
    
    for item in recommended:
        myfile.write(",%s" % item)
     

Distance : [[1.55431223e-15 4.94422473e-01 5.12465121e-01 5.25721913e-01
  5.27326314e-01 5.44148221e-01]]  Indice : [[  0 434 267 915 428 456]]
[1.55431223e-15 4.94422473e-01 5.12465121e-01 5.25721913e-01
 5.27326314e-01 5.44148221e-01]
6
Recommendation for movie_id
1       5.0
2       3.0
3       4.0
4       3.0
5       3.0
6       5.0
7       4.0
8       1.0
9       5.0
10      3.0
11      2.0
12      5.0
13      5.0
14      0.0
15      5.0
16      0.0
17      3.0
18      4.0
19      5.0
20      4.0
21      1.0
22      4.0
23      4.0
24      3.0
25      4.0
26      3.0
27      0.0
28      0.0
29      1.0
30      3.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0


Distance : [[1.11022302e-16 6.12357690e-01 6.39982790e-01 6.40922942e-01
  6.73547225e-01 6.98675229e-01]]  Indice : [[ 26  31 402  49  68 466]]
[1.11022302e-16 6.12357690e-01 6.39982790e-01 6.40922942e-01
 6.73547225e-01 6.98675229e-01]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       4.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0


Distance : [[2.22044605e-16 6.87134565e-01 6.88736636e-01 6.89693970e-01
  6.95537995e-01 7.00890339e-01]]  Indice : [[ 52 702 437 347 568 136]]
[2.22044605e-16 6.87134565e-01 6.88736636e-01 6.89693970e-01
 6.95537995e-01 7.00890339e-01]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       3.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      5.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      3.0
25      4.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0


Distance : [[0.         0.5874203  0.60959392 0.61404415 0.62988702 0.64199159]]  Indice : [[ 78  62 661 490 936 734]]
[0.         0.5874203  0.60959392 0.61404415 0.62988702 0.64199159]
6
Recommendation for movie_id
1       4.0
2       0.0
3       0.0
4       0.0
5       0.0
6       4.0
7       5.0
8       0.0
9       0.0
10      5.0
11      0.0
12      0.0
13      3.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      5.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 79, Length: 1649, dtype: float64:

1: 63, wit

Distance : [[0.         0.41377343 0.4531403  0.46649818 0.4710253  0.47109955]]  Indice : [[104 919 841 826 819 808]]
[0.         0.41377343 0.4531403  0.46649818 0.4710253  0.47109955]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 105, Length: 1649, dtype: float64:

1: 920, w

4: 472, with distance of 0.525325523576208:
5: 880, with distance of 0.5282980404708817:
[222, 487, 276, 472, 880]
Distance : [[0.         0.491369   0.54727672 0.579248   0.58951796 0.61975232]]  Indice : [[130   1 593 198 742 226]]
[0.         0.491369   0.54727672 0.579248   0.58951796 0.61975232]
6
Recommendation for movie_id
1       4.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       5.0
10      0.0
11      0.0
12      0.0
13      0.0
14      5.0
15      0.0
16      0.0
17      0.0
18      0.0
19      4.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    

2: 522, with distance of 0.6949815260839898:
3: 263, with distance of 0.6979878811857847:
4: 627, with distance of 0.7054313902074547:
5: 492, with distance of 0.7099565945512613:
[391, 522, 263, 627, 492]
Distance : [[6.66133815e-16 5.99448561e-01 6.09510227e-01 6.16405304e-01
  6.35607196e-01 6.35902903e-01]]  Indice : [[156 539 623  53 293  31]]
[6.66133815e-16 5.99448561e-01 6.09510227e-01 6.16405304e-01
 6.35607196e-01 6.35902903e-01]
6
Recommendation for movie_id
1       5.0
2       0.0
3       3.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      3.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.

Distance : [[0.         0.64019372 0.66656402 0.69679103 0.70619758 0.70870099]]  Indice : [[181 702 688 401 431 778]]
[0.         0.64019372 0.66656402 0.69679103 0.70619758 0.70870099]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      4.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 182, Length: 1649, dtype: float64:

1: 703, w

Distance : [[0.         0.56705417 0.62577486 0.63632867 0.63808373 0.64447596]]  Indice : [[208 734 130 198   1 936]]
[0.         0.56705417 0.62577486 0.63632867 0.63808373 0.64447596]
6
Recommendation for movie_id
1       5.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      3.0
15      0.0
16      4.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 209, Length: 1649, dtype: float64:

1: 735, w

4: 537, with distance of 0.47847214703448204:
5: 7, with distance of 0.48065457117174737:
[308, 85, 450, 537, 7]
Distance : [[0.         0.65198588 0.65612313 0.66112662 0.66851853 0.68315479]]  Indice : [[234   5  43 560 923 536]]
[0.         0.65198588 0.65612313 0.66112662 0.66851853 0.68315479]
6
Recommendation for movie_id
1       4.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       4.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      4.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.

Distance : [[0.         0.65317099 0.65411639 0.65412896 0.6545314  0.65625902]]  Indice : [[260 204 731 509 810 643]]
[0.         0.65317099 0.65411639 0.65412896 0.6545314  0.65625902]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 261, Length: 1649, dtype: float64:

1: 205, w

Distance : [[0.         0.63459448 0.64004088 0.64933278 0.66605298 0.66919644]]  Indice : [[287 262 537 923 390 296]]
[0.         0.63459448 0.64004088 0.64933278 0.66605298 0.66919644]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      4.0
13      5.0
14      0.0
15      4.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      5.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 288, Length: 1649, dtype: float64:

1: 263, w

Distance : [[0.         0.57039147 0.59811685 0.59958728 0.60074511 0.61488213]]  Indice : [[313 392 221 129 415 681]]
[0.         0.57039147 0.59811685 0.59958728 0.60074511 0.61488213]
6
Recommendation for movie_id
1       5.0
2       0.0
3       0.0
4       0.0
5       4.0
6       0.0
7       4.0
8       4.0
9       4.0
10      0.0
11      5.0
12      0.0
13      0.0
14      0.0
15      5.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      4.0
23      0.0
24      0.0
25      3.0
26      0.0
27      0.0
28      5.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 314, Length: 1649, dtype: float64:

1: 393, w

Distance : [[5.55111512e-16 6.21486154e-01 6.29257312e-01 6.32913242e-01
  6.42829114e-01 6.47681116e-01]]  Indice : [[337  17 382 150   5 665]]
[5.55111512e-16 6.21486154e-01 6.29257312e-01 6.32913242e-01
 6.42829114e-01 6.47681116e-01]
6
Recommendation for movie_id
1       3.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0


Distance : [[0.         0.52691172 0.53588459 0.55242379 0.55389315 0.5600128 ]]  Indice : [[362 275 863 428 415 513]]
[0.         0.52691172 0.53588459 0.55242379 0.55389315 0.5600128 ]
6
Recommendation for movie_id
1       0.0
2       4.0
3       0.0
4       0.0
5       1.0
6       0.0
7       3.0
8       0.0
9       3.0
10      0.0
11      5.0
12      5.0
13      0.0
14      0.0
15      0.0
16      0.0
17      4.0
18      0.0
19      0.0
20      0.0
21      0.0
22      3.0
23      0.0
24      3.0
25      3.0
26      0.0
27      0.0
28      4.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 363, Length: 1649, dtype: float64:

1: 276, w

Distance : [[4.44089210e-16 5.87279587e-01 6.16407157e-01 6.30044611e-01
  6.42344833e-01 6.51459188e-01]]  Indice : [[387 501 514  73 421  32]]
[4.44089210e-16 5.87279587e-01 6.16407157e-01 6.30044611e-01
 6.42344833e-01 6.51459188e-01]
6
Recommendation for movie_id
1       5.0
2       0.0
3       0.0
4       0.0
5       4.0
6       0.0
7       0.0
8       0.0
9       3.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0


1: 937, with distance of 0.4928688502907833:
2: 735, with distance of 0.5305442770341425:
3: 931, with distance of 0.546064661930015:
4: 569, with distance of 0.5478399043492641:
5: 192, with distance of 0.5740803225354879:
[937, 735, 931, 569, 192]
Distance : [[0.         0.49864888 0.56264096 0.5719482  0.57567046 0.57585077]]  Indice : [[413 104 239 808 919 111]]
[0.         0.49864888 0.56264096 0.5719482  0.57567046 0.57585077]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660 

3: 917, with distance of 0.6413817835653781:
4: 525, with distance of 0.6445655150064024:
5: 32, with distance of 0.6486431925654635:
[150, 624, 917, 525, 32]
Distance : [[2.22044605e-16 7.24747977e-01 7.24914508e-01 7.31233970e-01
  7.38372024e-01 7.38651290e-01]]  Indice : [[439 427 786 132 146 893]]
[2.22044605e-16 7.24747977e-01 7.24914508e-01 7.31233970e-01
 7.38372024e-01 7.38651290e-01]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0

1: 936, with distance of 0.5909467852478916:
2: 104, with distance of 0.6044790368334134:
3: 63, with distance of 0.6304656038539871:
4: 569, with distance of 0.6311415920372391:
5: 634, with distance of 0.6319222044432515:
[936, 104, 63, 569, 634]
Distance : [[0.         0.63194273 0.63389463 0.63406394 0.64311338 0.64312478]]  Indice : [[463 852 809 857 528 445]]
[0.         0.63194273 0.63389463 0.63406394 0.64311338 0.64312478]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      5.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660  

Distance : [[0.         0.47704248 0.49963334 0.51793937 0.52212094 0.52334286]]  Indice : [[488 586 450 350 862 615]]
[0.         0.47704248 0.49963334 0.51793937 0.52212094 0.52334286]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 489, Length: 1649, dtype: float64:

1: 587, w

Distance : [[0.         0.48057943 0.48310095 0.50070582 0.51578513 0.52262918]]  Indice : [[514 399 672 178 645  99]]
[0.         0.48057943 0.48310095 0.50070582 0.51578513 0.52262918]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 515, Length: 1649, dtype: float64:

1: 400, w

1: 786, with distance of 0.5335554017226379:
2: 933, with distance of 0.5538115998857814:
3: 508, with distance of 0.5613416245001435:
4: 738, with distance of 0.5673174520980576:
5: 457, with distance of 0.5731804909947771:
[786, 933, 508, 738, 457]
Distance : [[0.         0.70575251 0.70715991 0.70982836 0.71173603 0.71285422]]  Indice : [[538 390  84 304 320 666]]
[0.         0.70575251 0.70715991 0.70982836 0.71173603 0.71285422]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      5.0
20      0.0
21      0.0
22      3.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660

Distance : [[0.         0.6675576  0.66832916 0.67686986 0.68692865 0.69082853]]  Indice : [[562 437 575 529  77  29]]
[0.         0.6675576  0.66832916 0.67686986 0.68692865 0.69082853]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 563, Length: 1649, dtype: float64:

1: 438, w

Distance : [[0.         0.54817157 0.57455897 0.57934498 0.58198068 0.58284483]]  Indice : [[587  42 863 377 415 795]]
[0.         0.54817157 0.57455897 0.57934498 0.58198068 0.58284483]
6
Recommendation for movie_id
1       4.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       3.0
8       0.0
9       0.0
10      0.0
11      0.0
12      5.0
13      0.0
14      0.0
15      5.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      5.0
22      5.0
23      0.0
24      2.0
25      4.0
26      0.0
27      0.0
28      5.0
29      3.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 588, Length: 1649, dtype: float64:

1: 43, wi

Recommendation for movie_id
1       4.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      5.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      3.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 613, Length: 1649, dtype: float64:

1: 691, with distance of 0.7126384441737984:
2: 465, with distance of 0.7231080557288057:
3: 913, with distance of 0.7337183771795737:
4: 610, with distance of 0.7355403632227518:
5: 391, with dista

Distance : [[1.44328993e-15 6.23292254e-01 6.30910031e-01 6.35524337e-01
  6.40405107e-01 6.41153248e-01]]  Indice : [[638 536  17 353 502 877]]
[1.44328993e-15 6.23292254e-01 6.30910031e-01 6.35524337e-01
 6.40405107e-01 6.41153248e-01]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      3.0
13      0.0
14      5.0
15      0.0
16      0.0
17      0.0
18      0.0
19      4.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      4.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0


Distance : [[0.         0.58024146 0.58786565 0.59784046 0.59975782 0.60216284]]  Indice : [[663  17 150 822 307 931]]
[0.         0.58024146 0.58786565 0.59784046 0.59975782 0.60216284]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       4.0
5       0.0
6       0.0
7       3.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      2.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 664, Length: 1649, dtype: float64:

1: 18, wi

Distance : [[3.33066907e-16 6.28201373e-01 6.31156797e-01 6.33531833e-01
  6.51228304e-01 6.55734856e-01]]  Indice : [[689  86 863 300 642  55]]
[3.33066907e-16 6.28201373e-01 6.31156797e-01 6.33531833e-01
 6.51228304e-01 6.55734856e-01]
6
Recommendation for movie_id
1       4.0
2       0.0
3       0.0
4       3.0
5       0.0
6       0.0
7       0.0
8       0.0
9       3.0
10      0.0
11      0.0
12      4.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      3.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0


1: 487, with distance of 0.5033268403240141:
2: 222, with distance of 0.517498249705044:
3: 933, with distance of 0.5319270331163218:
4: 484, with distance of 0.532602434012547:
5: 916, with distance of 0.5374059881093247:
[487, 222, 933, 484, 916]
Distance : [[0.         0.42050658 0.4416062  0.45634499 0.47582813 0.47908906]]  Indice : [[715 312 150 397 449 270]]
[0.         0.42050658 0.4416062  0.45634499 0.47582813 0.47908906]
6
Recommendation for movie_id
1       5.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      4.0
12      0.0
13      2.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      5.0
23      4.0
24      0.0
25      4.0
26      0.0
27      0.0
28      5.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660  

Distance : [[0.         0.41491484 0.43247344 0.46602526 0.49071688 0.49161783]]  Indice : [[739 543 407 826 790 257]]
[0.         0.41491484 0.43247344 0.46602526 0.49071688 0.49161783]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 740, Length: 1649, dtype: float64:

1: 544, w

Distance : [[1.77635684e-15 5.10953876e-01 5.16041122e-01 5.16950164e-01
  5.21140314e-01 5.24275893e-01]]  Indice : [[765 312   6 649 325 693]]
[1.77635684e-15 5.10953876e-01 5.16041122e-01 5.16950164e-01
 5.21140314e-01 5.24275893e-01]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       5.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      3.0
23      4.0
24      0.0
25      0.0
26      0.0
27      0.0
28      5.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0


Distance : [[0.         0.55818251 0.60420697 0.61662948 0.62104792 0.63971165]]  Indice : [[791 276 633 402 524 539]]
[0.         0.55818251 0.60420697 0.61662948 0.62104792 0.63971165]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       4.0
8       0.0
9       3.0
10      0.0
11      0.0
12      0.0
13      4.0
14      0.0
15      4.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      3.0
22      0.0
23      0.0
24      3.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 792, Length: 1649, dtype: float64:

1: 277, w

2: 255, with distance of 0.5438686152390582:
3: 372, with distance of 0.5650814500896542:
4: 604, with distance of 0.5780996699693373:
5: 422, with distance of 0.5854992852623975:
[21, 255, 372, 604, 422]
Distance : [[4.44089210e-16 5.25951833e-01 5.28956077e-01 5.39312346e-01
  5.54516949e-01 5.57959309e-01]]  Indice : [[814 863 312 649 737 715]]
[4.44089210e-16 5.25951833e-01 5.28956077e-01 5.39312346e-01
 5.54516949e-01 5.57959309e-01]
6
Recommendation for movie_id
1       0.0
2       3.0
3       0.0
4       0.0
5       0.0
6       0.0
7       4.0
8       0.0
9       4.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      4.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0

1: 654, with distance of 0.6218429566373251:
2: 883, with distance of 0.6298972583518827:
3: 738, with distance of 0.6340748511550716:
4: 43, with distance of 0.6397805720804606:
5: 465, with distance of 0.6401275135606628:
[654, 883, 738, 43, 465]
Distance : [[0.         0.64232193 0.65409629 0.66311386 0.68288416 0.68372781]]  Indice : [[838 633 485 180 623 539]]
[0.         0.64232193 0.65409629 0.66311386 0.68288416 0.68372781]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       2.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660  

Distance : [[2.22044605e-16 4.85492058e-01 4.86605394e-01 4.95590914e-01
  5.03465814e-01 5.08398849e-01]]  Indice : [[862 723 205 283 610  99]]
[2.22044605e-16 4.85492058e-01 4.86605394e-01 4.95590914e-01
 5.03465814e-01 5.08398849e-01]
6
Recommendation for movie_id
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    1.0
1680    2.0
1681    0.0
1682    0.0


Distance : [[0.         0.52498692 0.53200319 0.53446962 0.54530407 0.5466895 ]]  Indice : [[885 932 681 863 428 275]]
[0.         0.52498692 0.53200319 0.53446962 0.54530407 0.5466895 ]
6
Recommendation for movie_id
1       4.0
2       4.0
3       3.0
4       3.0
5       3.0
6       0.0
7       0.0
8       0.0
9       5.0
10      3.0
11      5.0
12      0.0
13      0.0
14      0.0
15      3.0
16      0.0
17      4.0
18      0.0
19      0.0
20      2.0
21      0.0
22      4.0
23      0.0
24      4.0
25      0.0
26      4.0
27      2.0
28      4.0
29      1.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0
Name: 886, Length: 1649, dtype: float64:

1: 933, w

Distance : [[5.55111512e-16 5.88137910e-01 6.26111225e-01 6.26262626e-01
  6.26469514e-01 6.26602733e-01]]  Indice : [[909 662 547 799 431  25]]
[5.55111512e-16 5.88137910e-01 6.26111225e-01 6.26262626e-01
 6.26469514e-01 6.26602733e-01]
6
Recommendation for movie_id
1       0.0
2       0.0
3       2.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      4.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      4.0
24      3.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655    0.0
1656    0.0
1658    0.0
1659    0.0
1660    0.0
1661    0.0
1662    0.0
1663    0.0
1664    0.0
1665    0.0
1668    0.0
1669    0.0
1670    0.0
1671    0.0
1672    0.0
1674    0.0
1677    0.0
1678    0.0
1680    0.0
1681    0.0
1682    0.0



1: 64, with distance of 0.5097108855920462:
2: 886, with distance of 0.5249869247045857:
3: 653, with distance of 0.5251268907544304:
4: 87, with distance of 0.5252129634951446:
5: 198, with distance of 0.5275302928289775:
[64, 886, 653, 87, 198]
Distance : [[4.44089210e-16 5.61026547e-01 5.85730676e-01 5.94933303e-01
  5.99461218e-01 6.02134154e-01]]  Indice : [[933  84 715 150 693   6]]
[4.44089210e-16 5.61026547e-01 5.85730676e-01 5.94933303e-01
 5.99461218e-01 6.02134154e-01]
6
Recommendation for movie_id
1       2.0
2       4.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      4.0
26      0.0
27      0.0
28      0.0
29      0.0
30      0.0
       ... 
1644    0.0
1645    0.0
1646    0.0
1647    0.0
1648    0.0
1651    0.0
1652    0.0
1653    0.0
1654    0.0
1655